# Generated by Django 4.1.4 on 2022-12-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='det_desc',
            new_name='details_description',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='det_tit',
            new_name='details_title',
        ),
    ]
