# Generated by Django 4.1.4 on 2022-12-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_det_desc_details_details_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='details_description',
            new_name='detail_description',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='details_title',
            new_name='detail_title',
        ),
    ]
