# Generated by Django 4.1.4 on 2022-12-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_details_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='detail_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='detail_title',
            new_name='title',
        ),
    ]
