# Generated by Django 4.1.4 on 2022-12-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_about_alter_detail_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='feature',
        ),
    ]
