# Generated by Django 4.1.4 on 2022-12-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='image',
            field=models.ImageField(default=2, upload_to='detailsimg'),
            preserve_default=False,
        ),
    ]
